# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_item', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouth_taste', models.CharField(choices=[('Sweet', 'Sweet'), ('Salty', 'Salty'), ('Sour', 'Sour'), ('Bitter', 'Bitter'), ('Umami', 'Umami'), ('Spicy', 'Spicy'), ('Numbing', 'Numbing'), ('Cooling', 'Cooling')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tastes',
            field=models.ManyToManyField(to='flavors.Taste'),
        ),
    ]
