# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='base_item',
            new_name='listed_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='umbrella_cat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='altname',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavors.Ingredient'),
        ),
    ]
