# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0003_auto_20170507_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('submittor', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='tastes',
            field=models.ManyToManyField(blank=True, to='flavors.Taste'),
        ),
        migrations.AlterField(
            model_name='taste',
            name='mouth_taste',
            field=models.CharField(choices=[('sweet', 'sweet'), ('salty', 'salty'), ('sour', 'sour'), ('bitter', 'bitter'), ('umami', 'umami'), ('spicy', 'spicy'), ('numbing', 'numbing'), ('cooling', 'cooling')], max_length=20),
        ),
        migrations.AddField(
            model_name='combination',
            name='ingredients',
            field=models.ManyToManyField(to='flavors.Ingredient'),
        ),
    ]
