# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0004_auto_20170510_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.CharField(help_text='Submit a new ingredient to be able to pick for new flavor combinations.', max_length=100, verbose_name='New Ingredient Submission')),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('submittor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['listed_name']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='listed_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
