# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0006_auto_20170524_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='tastes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='umbrella_cat',
        ),
        migrations.DeleteModel(
            name='Taste',
        ),
    ]
